version: "3.8"
services:
  postgresdb:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=api_hub
  backend:
    image: backend-server
    build: .
    ports:
      - 8080:8080
    env_file:
      - ./.env
    depends_on:
      - postgresdb
